@baseUrl = http://127.0.0.1
@cType = application/json
@token = password
@value = password

### ROUTE API CUSTOMERS

### Get all order items
GET {{baseUrl}}/api/v1/orderitem
Content-Type: {{cType}}
{{token}}: {{value}}

### Create a new order item
POST {{baseUrl}}/api/v1/orderitem
Content-Type: {{cType}}
{{token}}: {{value}}

{
    "order_id": 2,
    "product_id": 1,
    "quantity": 5
}

### Update order item by ID
PUT {{baseUrl}}/api/v1/orderitem/2
Content-Type: {{cType}}
{{token}}: {{value}}

{
    "order_id": 2,
    "product_id": 2,
    "quantity": 10
}

### Get order item by ID
GET {{baseUrl}}/api/v1/orderitem/2
Content-Type: {{cType}}
{{token}}: {{value}}

### Delete an order item
DELETE {{baseUrl}}/api/v1/orderitem/2
Content-Type: {{cType}}
{{token}}: {{value}}

### Show data join
GET {{baseUrl}}/api/v1/orderitem-join
Content-Type: {{cType}}
{{token}}: {{value}}

### Show data join by ID
GET {{baseUrl}}/api/v1/orderitem-join/2
Content-Type: {{cType}}
{{token}}: {{value}}
