@baseUrl = http://127.0.0.1
@cType = application/json
@token = password
@value = password

### ROUTE API CUSTOMERS

### get request customers
GET {{baseUrl}}/api/v1/customers/
Content-Type: {{cType}}
{{token}}: {{value}}

### INI BUAT GET DATA customers BY ID
GET {{baseUrl}}/api/v1/customers/1
Content-Type: {{cType}}
{{token}}: {{value}}

### post request customers
POST {{baseUrl}}/api/v1/customers/
Content-Type: {{cType}}
{{token}}: {{value}}

{
    "full_name": "John Doe",
    "username": "johndoe",
    "email": "johndoe@example.com",
    "phone_number": "1234567890"
}

### put request customers by ID
PUT {{baseUrl}}/api/v1/customers/1
Content-Type: {{cType}}
{{token}}: {{value}}

{
    "full_name": "johniiii doe",
    "username": "johndoe",
    "email": "johnniiiidoee@gmail.com",
    "phone_number": "1234567890"
}

### delete request customers by ID
DELETE {{baseUrl}}/api/v1/customers/1
Content-Type: {{cType}}
{{token}}: {{value}}
