@baseUrl = http://127.0.0.1
@cType = application/json
@token = password
@value = password

### ROUTE API PAYMENT

### get request payment
GET {{baseUrl}}/api/v1/payment/
Content-Type: {{cType}}
{{token}}: {{value}}

### INI BUAT GET DATA payment BY ID
GET {{baseUrl}}/api/v1/payment/1
Content-Type: {{cType}}
{{token}}: {{value}}

### post request payment
POST {{baseUrl}}/api/v1/payment/
Content-Type: {{cType}}
{{token}}: {{value}}

{
  "data": {
    "attributes": {
      "order_id": "1",
      "payment_type": "bank_transfer",
      "transaction_details": {
        "order_id": "1",
        "gross_amount": 44000
      },
      "bank_transfer": {
        "bank": "bca"
      }
    }
  }
}


### delete request payment by ID
DELETE {{baseUrl}}/api/v1/payment/1
Content-Type: {{cType}}
{{token}}: {{value}}
